// next/lib/promptCategoriesData.ts
// Dataset state klasifikasi prompt rekomendasi topik pembelajaran berstruktur.

export type CategoryId = "sd" | "smp" | "sma" | "kuliah" | "ngoding" | "skill";

export type SubCategory = {
  id: string;
  name: string;
};

export type MainCategory = {
  id: CategoryId;
  name: string;
  icon: string; // Bootstrap icon class e.g. "bi-book"
  description: string;
  subCategories: SubCategory[];
};

export type PromptItem = {
  id: string;
  title: string;
  reason: string;
  categoryId: CategoryId;
  subCategoryId: string;
  promptText: string;
  badge?: string;
};

export const MAIN_CATEGORIES: MainCategory[] = [
  {
    id: "sd",
    name: "Sekolah Dasar (SD)",
    icon: "bi-backpack",
    description: "Materi pelajaran SD mulai dari Kelas 1 sampai Kelas 6.",
    subCategories: [
      { id: "sd-all", name: "Semua Kelas SD" },
      { id: "kelas-1", name: "Kelas 1" },
      { id: "kelas-2", name: "Kelas 2" },
      { id: "kelas-3", name: "Kelas 3" },
      { id: "kelas-4", name: "Kelas 4" },
      { id: "kelas-5", name: "Kelas 5" },
      { id: "kelas-6", name: "Kelas 6" },
    ],
  },
  {
    id: "smp",
    name: "SMP",
    icon: "bi-mortarboard",
    description: "Materi pelajaran SMP berklasifikasi subjek pilihan.",
    subCategories: [
      { id: "smp-all", name: "Semua Subjek SMP" },
      { id: "smp-ipa", name: "IPA" },
      { id: "smp-ips", name: "IPS" },
      { id: "smp-mat", name: "Matematika" },
      { id: "smp-indo", name: "Bahasa Indonesia" },
      { id: "smp-ing", name: "Bahasa Inggris" },
      { id: "smp-tik", name: "Informatika / TIK" },
    ],
  },
  {
    id: "sma",
    name: "SMA / SMK",
    icon: "bi-bank",
    description: "Materi SMA peminatan IPA, IPS, Matematika, dan Bahasa.",
    subCategories: [
      { id: "sma-all", name: "Semua Jurusan SMA" },
      { id: "sma-ipa", name: "IPA (Fisika, Kimia, Biologi)" },
      { id: "sma-ips", name: "IPS (Ekonomi, Geografi, Sosiologi)" },
      { id: "sma-mat", name: "Matematika Lanjutan" },
      { id: "sma-bahasa", name: "Bahasa & Sastra" },
    ],
  },
  {
    id: "kuliah",
    name: "Materi Kuliah",
    icon: "bi-building",
    description: "Mata kuliah tingkat perguruan tinggi berdasarkan bidang ilmu.",
    subCategories: [
      { id: "kuliah-all", name: "Semua Jurusan Kuliah" },
      { id: "kuliah-it", name: "Informatika & Data" },
      { id: "kuliah-teknik", name: "Teknik & Rekayasa" },
      { id: "kuliah-ekonomi", name: "Ekonomi & Bisnis" },
      { id: "kuliah-kesehatan", name: "Kedokteran & Kesehatan" },
      { id: "kuliah-mipa", name: "MIPA & Sains" },
      { id: "kuliah-sosial", name: "Hukum & Sosial" },
    ],
  },
  {
    id: "ngoding",
    name: "Ngoding & IT",
    icon: "bi-code-slash",
    description: "Panduan belajar pemrograman dari dasar hingga spesialisasi.",
    subCategories: [
      { id: "ngoding-all", name: "Semua Topik Koding" },
      { id: "ngoding-pemula", name: "Dasar & Pemula" },
      { id: "ngoding-web", name: "Web Development" },
      { id: "ngoding-mobile", name: "Mobile App" },
      { id: "ngoding-data", name: "Data Science & AI" },
      { id: "ngoding-backend", name: "Backend & Database" },
      { id: "ngoding-game", name: "Game Development" },
    ],
  },
  {
    id: "skill",
    name: "Skill & Keterampilan",
    icon: "bi-stars",
    description: "Pengembangan diri, bahasa asing, dan keterampilan praktis.",
    subCategories: [
      { id: "skill-all", name: "Semua Keterampilan" },
      { id: "skill-bahasa", name: "Bahasa Asing" },
      { id: "skill-desain", name: "Desain & Visual" },
      { id: "skill-public-speaking", name: "Public Speaking" },
      { id: "skill-finance", name: "Keuangan & Bisnis" },
    ],
  },
];

export const PROMPT_ITEMS: PromptItem[] = [
  // ==================== SD KELAS 1 ====================
  {
    id: "sd-1-1",
    title: "Matematika Kelas 1: Penjumlahan & Pengurangan Angka 1-20",
    reason: "Pengenalan angka dan operasi hitung dasar sederhana.",
    categoryId: "sd",
    subCategoryId: "kelas-1",
    promptText: "Matematika Kelas 1 SD: Belajar Menjumlahkan dan Mengurangi Angka 1 sampai 20 dengan Visual Sederhana",
    badge: "Kelas 1 SD",
  },
  {
    id: "sd-1-2",
    title: "Bahasa Indonesia Kelas 1: Membaca Suku Kata & Abjad",
    reason: "Membangun kelancaran membaca bagi anak usia dini.",
    categoryId: "sd",
    subCategoryId: "kelas-1",
    promptText: "Bahasa Indonesia Kelas 1 SD: Mengenal Huruf Abjad dan Membaca Suku Kata Sederhana",
    badge: "Kelas 1 SD",
  },
  {
    id: "sd-1-3",
    title: "Pendidikan Pancasila Kelas 1: Simbol Garuda & Gotong Royong",
    reason: "Mengenal sila-sila Pancasila dan perilaku terpuji di sekolah.",
    categoryId: "sd",
    subCategoryId: "kelas-1",
    promptText: "Pendidikan Pancasila Kelas 1 SD: Mengenal Simbol Sila Pancasila dan Contoh Sikap Gotong Royong",
    badge: "Kelas 1 SD",
  },
  {
    id: "sd-1-4",
    title: "Bahasa Inggris Kelas 1: Greeting & Names of Animals",
    reason: "Kosa kata Bahasa Inggris dasar untuk percakapan awal.",
    categoryId: "sd",
    subCategoryId: "kelas-1",
    promptText: "Bahasa Inggris Kelas 1 SD: Belajar Menyapa (Greeting) dan Nama-nama Hewan dalam Bahasa Inggris",
    badge: "Kelas 1 SD",
  },
  {
    id: "sd-1-5",
    title: "Seni Budaya Kelas 1: Mengenal Warna Primer & Bentuk Dasar",
    reason: "Pengenalan warna merah, kuning, biru, serta bentuk lingkaran & persegi.",
    categoryId: "sd",
    subCategoryId: "kelas-1",
    promptText: "Seni Budaya Kelas 1 SD: Mengenal Warna Primer dan Menggambar Bentuk Bangun Datar Dasar",
    badge: "Kelas 1 SD",
  },

  // ==================== SD KELAS 2 ====================
  {
    id: "sd-2-1",
    title: "Matematika Kelas 2: Pengenalan Perkalian Sederhana",
    reason: "Pemahaman konsep penjumlahan berulang sebagai dasar perkalian.",
    categoryId: "sd",
    subCategoryId: "kelas-2",
    promptText: "Matematika Kelas 2 SD: Konsep Dasar Perkalian Sebagai Penjumlahan Berulang",
    badge: "Kelas 2 SD",
  },
  {
    id: "sd-2-2",
    title: "IPAS Kelas 2: Mengenal Anggota Tubuh & Panca Indra",
    reason: "Mengenal fungsi organ tubuh manusia dalam kehidupan sehari-hari.",
    categoryId: "sd",
    subCategoryId: "kelas-2",
    promptText: "IPAS Kelas 2 SD: Mengenal Bagian Tubuh dan Fungsi Panca Indra Manusia",
    badge: "Kelas 2 SD",
  },
  {
    id: "sd-2-3",
    title: "Matematika Kelas 2: Pembagian Sebagai Pengurangan Berulang",
    reason: "Memahami konsep pembagian dasar secara konkret.",
    categoryId: "sd",
    subCategoryId: "kelas-2",
    promptText: "Matematika Kelas 2 SD: Memahami Konsep Pembagian Sederhana Sebagai Pengurangan Berulang",
    badge: "Kelas 2 SD",
  },
  {
    id: "sd-2-4",
    title: "Bahasa Indonesia Kelas 2: Menulis Kalimat Efektif & Tanda Baca",
    reason: "Penggunaan huruf kapital, titik, dan tanda tanya.",
    categoryId: "sd",
    subCategoryId: "kelas-2",
    promptText: "Bahasa Indonesia Kelas 2 SD: Aturan Aturan Huruf Kapital dan Penggunaan Tanda Baca Titik serta Tanda Tanya",
    badge: "Kelas 2 SD",
  },
  {
    id: "sd-2-5",
    title: "IPAS Kelas 2: Benda Padat, Cair, dan Gas di Sekitar Kita",
    reason: "Mengenal wujud benda dan sifat-sifat fisiknya.",
    categoryId: "sd",
    subCategoryId: "kelas-2",
    promptText: "IPAS Kelas 2 SD: Mengenal Perubahan Wujud Benda Padat, Cair, dan Gas dalam Kehidupan Sehari-hari",
    badge: "Kelas 2 SD",
  },

  // ==================== SD KELAS 3 ====================
  {
    id: "sd-3-1",
    title: "IPAS Kelas 3: Ciri-ciri & Kebutuhan Makhluk Hidup",
    reason: "Memahami perbedaan tumbuhan, hewan, dan manusia.",
    categoryId: "sd",
    subCategoryId: "kelas-3",
    promptText: "IPAS Kelas 3 SD: Mengenal Ciri-ciri Makhluk Hidup dan Kebutuhan Dasarnya",
    badge: "Kelas 3 SD",
  },
  {
    id: "sd-3-2",
    title: "Matematika Kelas 3: Pecahan Sederhana (1/2, 1/3, 1/4)",
    reason: "Pengenalan pecahan dasar menggunakan benda konkret.",
    categoryId: "sd",
    subCategoryId: "kelas-3",
    promptText: "Matematika Kelas 3 SD: Memahami Konsep Pecahan Sederhana 1/2, 1/3, dan 1/4",
    badge: "Kelas 3 SD",
  },
  {
    id: "sd-3-3",
    title: "Matematika Kelas 3: Pengukuran Waktu, Panjang, dan Berat",
    reason: "Membaca jam digital/analog serta menggunakan penggaris & timbangan.",
    categoryId: "sd",
    subCategoryId: "kelas-3",
    promptText: "Matematika Kelas 3 SD: Panduan Membaca Jam dan Menghitung Satuan Panjang serta Berat Benda",
    badge: "Kelas 3 SD",
  },
  {
    id: "sd-3-4",
    title: "IPAS Kelas 3: Ekosistem & Rantai Makanan",
    reason: "Peran produsen, konsumen, dan pengurai di alam.",
    categoryId: "sd",
    subCategoryId: "kelas-3",
    promptText: "IPAS Kelas 3 SD: Mengenal Hubungan Rantai Makanan dan Peran Makhluk Hidup dalam Ekosistem",
    badge: "Kelas 3 SD",
  },
  {
    id: "sd-3-5",
    title: "Pendidikan Pancasila Kelas 3: Hak dan Kewajiban",
    reason: "Memahami hak dan kewajiban anak di rumah dan sekolah.",
    categoryId: "sd",
    subCategoryId: "kelas-3",
    promptText: "Pendidikan Pancasila Kelas 3 SD: Perbedaan Hak dan Kewajiban Anak di Rumah serta Sekolah",
    badge: "Kelas 3 SD",
  },

  // ==================== SD KELAS 4 ====================
  {
    id: "sd-4-1",
    title: "IPAS Kelas 4: Fotosintesis & Proses Pembuatan Makanan Tumbuhan",
    reason: "Konsep utama IPA dasar di Sekolah Dasar Kurikulum Merdeka.",
    categoryId: "sd",
    subCategoryId: "kelas-4",
    promptText: "IPAS Kelas 4 SD: Bagaimana Tumbuhan Memasak Makanan Melalui Proses Fotosintesis",
    badge: "Kelas 4 SD",
  },
  {
    id: "sd-4-2",
    title: "Matematika Kelas 4: Keliling & Luas Bangun Datar",
    reason: "Menghitung luas persegi, persegi panjang, dan segitiga.",
    categoryId: "sd",
    subCategoryId: "kelas-4",
    promptText: "Matematika Kelas 4 SD: Panduan Menghitung Keliling dan Luas Bangun Datar",
    badge: "Kelas 4 SD",
  },
  {
    id: "sd-4-3",
    title: "IPAS Kelas 4: Perubahan Bentuk Energi",
    reason: "Energi listrik menjadi panas, gerak, dan cahaya.",
    categoryId: "sd",
    subCategoryId: "kelas-4",
    promptText: "IPAS Kelas 4 SD: Contoh Perubahan Bentuk Energi dalam Alat-Alat Rumah Tangga",
    badge: "Kelas 4 SD",
  },
  {
    id: "sd-4-4",
    title: "Bahasa Indonesia Kelas 4: Menemukan Gagasan Utama Paragraf",
    reason: "Melatih kemampuan membaca kritis dan merangkum isi bacaan.",
    categoryId: "sd",
    subCategoryId: "kelas-4",
    promptText: "Bahasa Indonesia Kelas 4 SD: Cara Menentukan Gagasan Utama dan Gagasan Pendukung Paragraf",
    badge: "Kelas 4 SD",
  },
  {
    id: "sd-4-5",
    title: "IPAS Kelas 4: Kerajaan Hindu, Buddha, dan Islam di Indonesia",
    reason: "Sejarah lokal nusantara dan peninggalan bersejarah.",
    categoryId: "sd",
    subCategoryId: "kelas-4",
    promptText: "IPAS Kelas 4 SD: Mengenal Sejarah Kerajaan Hindu, Buddha, dan Islam di Indonesia",
    badge: "Kelas 4 SD",
  },

  // ==================== SD KELAS 5 ====================
  {
    id: "sd-5-1",
    title: "IPAS Kelas 5: Sistem Pencernaan pada Manusia",
    reason: "Materi favorit Ujian Sekolah SD mengenai organ pencernaan.",
    categoryId: "sd",
    subCategoryId: "kelas-5",
    promptText: "IPAS Kelas 5 SD: Organ dan Proses Sistem Pencernaan Manusia dari Mulut hingga Usus",
    badge: "Kelas 5 SD",
  },
  {
    id: "sd-5-2",
    title: "Matematika Kelas 5: Operasi Hitung Pecahan Biasa & Campuran",
    reason: "Keterampilan penjumlahan dan pengurangan pecahan beda penyebut.",
    categoryId: "sd",
    subCategoryId: "kelas-5",
    promptText: "Matematika Kelas 5 SD: Operasi Hitung Penjumlahan dan Pengurangan Pecahan",
    badge: "Kelas 5 SD",
  },
  {
    id: "sd-5-3",
    title: "IPAS Kelas 5: Organ Peredaran Darah Manusia & Jantung",
    reason: "Mekanisme peredaran darah besar dan kecil.",
    categoryId: "sd",
    subCategoryId: "kelas-5",
    promptText: "IPAS Kelas 5 SD: Cara Kerja Jantung dan Sistem Peredaran Darah Manusia",
    badge: "Kelas 5 SD",
  },
  {
    id: "sd-5-4",
    title: "Matematika Kelas 5: Skala, Peta, dan Denah",
    reason: "Menghitung jarak sebenarnya dari jarak pada peta.",
    categoryId: "sd",
    subCategoryId: "kelas-5",
    promptText: "Matematika Kelas 5 SD: Rumus Skala Peta dan Cara Menghitung Jarak Sebenarnya",
    badge: "Kelas 5 SD",
  },
  {
    id: "sd-5-5",
    title: "IPAS Kelas 5: Sifat-Sifat Cahaya & Pembentukan Bayangan",
    reason: "Merambat lurus, menembus benda bening, dan dipantulkan.",
    categoryId: "sd",
    subCategoryId: "kelas-5",
    promptText: "IPAS Kelas 5 SD: Mengenal Sifat-Sifat Cahaya dan Percobaan Sederhana di Rumah",
    badge: "Kelas 5 SD",
  },

  // ==================== SD KELAS 6 ====================
  {
    id: "sd-6-1",
    title: "Matematika Kelas 6: Bangun Ruang (Limas, Prisma, Tabung, Bola)",
    reason: "Menghitung volume dan luas permukaan bangun ruang 3D.",
    categoryId: "sd",
    subCategoryId: "kelas-6",
    promptText: "Matematika Kelas 6 SD: Menghitung Volume dan Luas Permukaan Bangun Ruang 3D",
    badge: "Kelas 6 SD",
  },
  {
    id: "sd-6-2",
    title: "IPAS Kelas 6: Tata Surya & Planet-planet",
    reason: "Eksplorasi urutan planet, rotasi, dan revolusi bumi.",
    categoryId: "sd",
    subCategoryId: "kelas-6",
    promptText: "IPAS Kelas 6 SD: Mengenal Sistem Tata Surya, Planet, Rotasi, dan Revolusi Bumi",
    badge: "Kelas 6 SD",
  },
  {
    id: "sd-6-3",
    title: "Matematika Kelas 6: Pengolahan Data (Rata-rata, Modus, Median)",
    reason: "Dasar statistika sederhana untuk kelulusan SD.",
    categoryId: "sd",
    subCategoryId: "kelas-6",
    promptText: "Matematika Kelas 6 SD: Menghitung Nilai Rata-rata (Mean), Modus, dan Nilai Tengah (Median)",
    badge: "Kelas 6 SD",
  },
  {
    id: "sd-6-4",
    title: "IPAS Kelas 6: Rangkaian Listrik Seri & Paralel",
    reason: "Perbedaan kelebihan dan kekurangan rangkaian seri vs paralel.",
    categoryId: "sd",
    subCategoryId: "kelas-6",
    promptText: "IPAS Kelas 6 SD: Perbedaan Rangkaian Listrik Seri dan Paralel Beserta Skema Gambarnya",
    badge: "Kelas 6 SD",
  },
  {
    id: "sd-6-5",
    title: "IPAS Kelas 6: Negara ASEAN & Kerja Sama Regional",
    reason: "Profil 10 negara pendiri dan anggota ASEAN.",
    categoryId: "sd",
    subCategoryId: "kelas-6",
    promptText: "IPAS Kelas 6 SD: Profil Negara-Negara ASEAN dan Bentuk Kerja Sama Indonesia di Asia Tenggara",
    badge: "Kelas 6 SD",
  },

  // ==================== SMP IPA ====================
  {
    id: "smp-ipa-1",
    title: "Fisika SMP: Hukum Gerak Newton I, II, dan III",
    reason: "Konsep dasar gaya dan percepatan benda.",
    categoryId: "smp",
    subCategoryId: "smp-ipa",
    promptText: "Fisika SMP: Memahami Hukum Newton tentang Gerak dan Contoh Penerapannya Sehari-hari",
    badge: "SMP IPA",
  },
  {
    id: "smp-ipa-2",
    title: "Biologi SMP: Sistem Pernapasan Manusia & Organ Paru-paru",
    reason: "Mekanisme inspirasi, ekspirasi, dan pertukaran gas O2 & CO2.",
    categoryId: "smp",
    subCategoryId: "smp-ipa",
    promptText: "Biologi SMP: Mekanisme Sistem Pernapasan Manusia dan Gangguan Paru-Paru",
    badge: "SMP IPA",
  },
  {
    id: "smp-ipa-3",
    title: "Fisika SMP: Cahaya, Cermin Cembung & Cekung",
    reason: "Pembentukan bayangan, pembiasan, dan hukum pemantulan cahaya.",
    categoryId: "smp",
    subCategoryId: "smp-ipa",
    promptText: "Fisika SMP: Sifat Cahaya dan Pembentukan Bayangan pada Cermin Cembung serta Cekung",
    badge: "SMP IPA",
  },
  {
    id: "smp-ipa-4",
    title: "Kimia SMP: Zat Aditif & Zat Adiktif dalam Makanan",
    reason: "Bahan pengawet, pewarna makanan, serta bahaya rokok dan narkoba.",
    categoryId: "smp",
    subCategoryId: "smp-ipa",
    promptText: "Kimia SMP: Mengenal Jenis Zat Aditif Alami/Buatan dalam Makanan dan Bahaya Zat Adiktif",
    badge: "SMP IPA",
  },
  {
    id: "smp-ipa-5",
    title: "Biologi SMP: Sistem Ekskresi Manusia (Ginjal, Hati, Kulit)",
    reason: "Proses pembentukan urine dan pengeluaran zat sisa metabolisme.",
    categoryId: "smp",
    subCategoryId: "smp-ipa",
    promptText: "Biologi SMP: Organ Sistem Ekskresi Manusia dan Tahapan Pembentukan Urine di Ginjal",
    badge: "SMP IPA",
  },

  // ==================== SMP IPS ====================
  {
    id: "smp-ips-1",
    title: "IPS SMP: Interaksi Sosial & Keragaman Budaya Indonesia",
    reason: "Bentuk interaksi asosiatif, disosiatif, dan integrasi sosial.",
    categoryId: "smp",
    subCategoryId: "smp-ips",
    promptText: "IPS SMP: Bentuk Interaksi Sosial dan Pengaruh Keragaman Budaya di Indonesia",
    badge: "SMP IPS",
  },
  {
    id: "smp-ips-2",
    title: "Geografi SMP: Peta, Atlas, dan Skala Wilayah Indonesia",
    reason: "Unsur-unsur peta dan letak astronomis serta geografis Indonesia.",
    categoryId: "smp",
    subCategoryId: "smp-ips",
    promptText: "Geografi SMP: Membaca Peta, Menghitung Skala, dan Pengaruh Letak Astronomis Indonesia",
    badge: "SMP IPS",
  },
  {
    id: "smp-ips-3",
    title: "Ekonomi SMP: Kelangkaan Sumber Daya & Kebutuhan Manusia",
    reason: "Faktor penyebab kelangkaan dan skala prioritas kebutuhan.",
    categoryId: "smp",
    subCategoryId: "smp-ips",
    promptText: "Ekonomi SMP: Konsep Kelangkaan Sumber Daya dan Cara Menyusun Skala Prioritas Kebutuhan",
    badge: "SMP IPS",
  },
  {
    id: "smp-ips-4",
    title: "Sejarah SMP: Kerajaan Islam & Jalur Rempah Nusantara",
    reason: "Masuknya Islam di Indonesia dan jalur perdagangan rempah.",
    categoryId: "smp",
    subCategoryId: "smp-ips",
    promptText: "Sejarah SMP: Perkembangan Kerajaan Islam dan Peran Jalur Rempah di Nusantara",
    badge: "SMP IPS",
  },

  // ==================== SMP MATEMATIKA ====================
  {
    id: "smp-mat-1",
    title: "Matematika SMP: Sistem Persamaan Linear Dua Variabel (SPLDV)",
    reason: "Metode eliminasi dan substitusi memecahkan persoalan cerita.",
    categoryId: "smp",
    subCategoryId: "smp-mat",
    promptText: "Matematika SMP: Cara Menyelesaikan Sistem Persamaan Linear Dua Variabel (SPLDV)",
    badge: "SMP Matematika",
  },
  {
    id: "smp-mat-2",
    title: "Matematika SMP: Teorema Pythagoras & Aplikasi Segitiga",
    reason: "Rumus c^2 = a^2 + b^2 pada segitiga siku-siku dan tripel Pythagoras.",
    categoryId: "smp",
    subCategoryId: "smp-mat",
    promptText: "Matematika SMP: Penerapan Teorema Pythagoras untuk Menghitung Panjang Sisi Segitiga Siku-Siku",
    badge: "SMP Matematika",
  },
  {
    id: "smp-mat-3",
    title: "Matematika SMP: Persamaan & Pertidaksamaan Linear Satu Variabel",
    reason: "Penyelesaian aljabar dasar untuk mencari variabel x.",
    categoryId: "smp",
    subCategoryId: "smp-mat",
    promptText: "Matematika SMP: Langkah Memecahkan Persamaan dan Pertidaksamaan Linear Satu Variabel (PTLSV)",
    badge: "SMP Matematika",
  },

  // ==================== SMP BAHASA INDONESIA & INGGRIS & TIK ====================
  {
    id: "smp-indo-1",
    title: "Bahasa Indonesia SMP: Teks Laporan Hasil Observasi (LHO)",
    reason: "Struktur teks LHO: Pernyataan umum, deskripsi bagian, dan manfaat.",
    categoryId: "smp",
    subCategoryId: "smp-indo",
    promptText: "Bahasa Indonesia SMP: Struktur dan Ciri Kebahasaan Teks Laporan Hasil Observasi (LHO)",
    badge: "SMP Bahasa",
  },
  {
    id: "smp-ing-1",
    title: "Bahasa Inggris SMP: Simple Present vs Present Continuous Tense",
    reason: "Membedakan kebiasaan umum dan aktivitas yang sedang berlangsung.",
    categoryId: "smp",
    subCategoryId: "smp-ing",
    promptText: "Bahasa Inggris SMP: Perbedaan Penggunaan Simple Present Tense dan Present Continuous Tense",
    badge: "SMP English",
  },
  {
    id: "smp-tik-1",
    title: "Informatika SMP: Berpikir Komputasional & Algoritma",
    reason: "Empat pilar CT: Dekomposisi, Pengenalan Pola, Abstraksi, dan Algoritma.",
    categoryId: "smp",
    subCategoryId: "smp-tik",
    promptText: "Informatika SMP: Mengenal 4 Pilar Berpikir Komputasional (Computational Thinking)",
    badge: "SMP TIK",
  },

  // ==================== SMA IPA ====================
  {
    id: "sma-ipa-1",
    title: "Fisika SMA: Dinamika Rotasi & Momen Inersia",
    reason: "Topik penting ujian kelulusan dan seleksi masuk perguruan tinggi.",
    categoryId: "sma",
    subCategoryId: "sma-ipa",
    promptText: "Fisika SMA Kelas 11: Konsep Dinamika Rotasi, Momen Inersia, dan Hukum Kekekalan Momentum Sudut",
    badge: "SMA Fisika",
  },
  {
    id: "sma-ipa-2",
    title: "Kimia SMA: Stoikiometri & Konsep Mol",
    reason: "Jantung dari perhitungan reaksi kimia dasar SMA.",
    categoryId: "sma",
    subCategoryId: "sma-ipa",
    promptText: "Kimia SMA Kelas 10: Menghitung Reaksi Kimia Menggunakan Konsep Mol dan Stoikiometri",
    badge: "SMA Kimia",
  },
  {
    id: "sma-ipa-3",
    title: "Biologi SMA: Genetika & Hukum Pewarisan Sifat Mendel",
    reason: "Memahami persilangan monohibrid, dihibrid, dan DNA/RNA.",
    categoryId: "sma",
    subCategoryId: "sma-ipa",
    promptText: "Biologi SMA Kelas 12: Konsep Genetika, Struktur DNA, dan Hukum Pewarisan Sifat Mendel",
    badge: "SMA Biologi",
  },
  {
    id: "sma-ipa-4",
    title: "Kimia SMA: Larutan Asam Basa, pH, & Titrasi",
    reason: "Menghitung pH asam/basa kuat dan lemah serta Kurva Titrasi.",
    categoryId: "sma",
    subCategoryId: "sma-ipa",
    promptText: "Kimia SMA Kelas 11: Menghitung Nilai pH Larutan Asam Basa dan Prinsip Titrasi Asam Basa",
    badge: "SMA Kimia",
  },
  {
    id: "sma-ipa-5",
    title: "Biologi SMA: Metabolisme Sel (Respirasi Aerob & Anaerob)",
    reason: "Glikolisis, Dekarboksilasi Oksidatif, Siklus Krebs, dan Transpor Elektron.",
    categoryId: "sma",
    subCategoryId: "sma-ipa",
    promptText: "Biologi SMA Kelas 12: Tahapan Respirasi Aerob Seluler dan Pembentukan ATP",
    badge: "SMA Biologi",
  },

  // ==================== SMA IPS ====================
  {
    id: "sma-ips-1",
    title: "Ekonomi SMA: Kebijakan Moneter & Kebijakan Fiskal",
    reason: "Instrumen pemerintah menangani inflasi dan pengangguran.",
    categoryId: "sma",
    subCategoryId: "sma-ips",
    promptText: "Ekonomi SMA Kelas 11: Perbedaan Kebijakan Moneter Bank Sentral dan Kebijakan Fiskal Pemerintah",
    badge: "SMA Ekonomi",
  },
  {
    id: "sma-ips-2",
    title: "Geografi SMA: Penginderaan Jauh & Sistem Informasi Geografis (SIG)",
    reason: "Pemanfaatan citra satelit untuk tata ruang wilayah.",
    categoryId: "sma",
    subCategoryId: "sma-ips",
    promptText: "Geografi SMA: Pemanfaatan Penginderaan Jauh dan SIG dalam Pemetaan Tata Ruang",
    badge: "SMA Geografi",
  },
  {
    id: "sma-ips-3",
    title: "Ekonomi SMA: Akuntansi Dasar & Jurnal Umum Perusahaan Jasa",
    reason: "Persamaan dasar akuntansi, siklus akuntansi, dan pembuatan jurnal.",
    categoryId: "sma",
    subCategoryId: "sma-ips",
    promptText: "Ekonomi SMA Kelas 12: Siklus Akuntansi Perusahaan Jasa dan Cara Pencatatan Jurnal Umum",
    badge: "SMA Ekonomi",
  },
  {
    id: "sma-ips-4",
    title: "Sosiologi SMA: Penyimpangan & Konflik Sosial",
    reason: "Bentuk-bentuk penyimpangan dan strategi resolusi konflik sosial.",
    categoryId: "sma",
    subCategoryId: "sma-ips",
    promptText: "Sosiologi SMA: Faktor Penyebab Konflik Sosial dan Bentuk Akomodasi Resolusi Konflik",
    badge: "SMA Sosiologi",
  },

  // ==================== SMA MATEMATIKA & BAHASA ====================
  {
    id: "sma-mat-1",
    title: "Matematika SMA: Turunan Fungsi Trigonometri & Aplikasinya",
    reason: "Turunan sinus, kosinus, serta menentukan titik stasioner.",
    categoryId: "sma",
    subCategoryId: "sma-mat",
    promptText: "Matematika Peminatan SMA: Turunan Fungsi Trigonometri dan Aplikasi Nilai Maksimum/Minimum",
    badge: "SMA Matematika",
  },
  {
    id: "sma-mat-2",
    title: "Matematika SMA: Matriks, Determinant & Invers 2x2/3x3",
    reason: "Operasi hitung matriks dan penggunaan invers dalam persamaan.",
    categoryId: "sma",
    subCategoryId: "sma-mat",
    promptText: "Matematika SMA: Menghitung Determinant dan Invers Matriks Ordo 2x2 serta 3x3",
    badge: "SMA Matematika",
  },
  {
    id: "sma-bahasa-1",
    title: "Bahasa & Sastra SMA: Teknik Debat & Menyusun Argumen",
    reason: "Membuat mosi, argumen afirmatif, oposisi, dan penutup.",
    categoryId: "sma",
    subCategoryId: "sma-bahasa",
    promptText: "Bahasa Indonesia SMA: Tata Cara Debat Formal dan Teknik Menyusun Argumen Berbasis Data",
    badge: "SMA Sastra",
  },

  // ==================== KULIAH INFORMATIKA ====================
  {
    id: "kuliah-it-1",
    title: "Struktur Data & Algoritma: Graph & Tree Traversal",
    reason: "Mata kuliah wajib Informatika & bekal coding interview.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-it",
    promptText: "Struktur Data & Algoritma: Implementasi Graph, Trees, BFS, dan DFS untuk Mahasiswa Informatika",
    badge: "Kuliah IT",
  },
  {
    id: "kuliah-it-2",
    title: "Kecerdasan Buatan: Neural Networks & Deep Learning",
    reason: "Pondasi arsitektur AI modern dan Convolutional Neural Networks.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-it",
    promptText: "Kecerdasan Buatan: Dasar-dasar Artificial Neural Networks (ANN) dan Arsitektur Deep Learning",
    badge: "Kuliah AI",
  },
  {
    id: "kuliah-it-3",
    title: "Basis Data Sistem: Normalisasi Database (1NF - 3NF)",
    reason: "Menghindari redundansi data dan anomaly dengan normalisasi.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-it",
    promptText: "Sistem Basis Data Kuliah: Panduan Normalisasi Database dari Form 1NF, 2NF hingga 3NF",
    badge: "Kuliah Database",
  },
  {
    id: "kuliah-it-4",
    title: "Jaringan Komputer: Arsitektur OSI Layer & Subnetting IP",
    reason: "Model 7 OSI layer, TCP/IP, serta perhitungan subnet mask IPv4.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-it",
    promptText: "Jaringan Komputer: Memahami 7 Layer OSI Model dan Cara Menghitung Subnetting IP Address",
    badge: "Kuliah Network",
  },

  // ==================== KULIAH TEKNIK & EKONOMI ====================
  {
    id: "kuliah-teknik-1",
    title: "Termodinamika Teknik: Hukum 1 & 2 Termodinamika",
    reason: "Mata kuliah dasar Teknik Mesin, Kimia, dan Elektro.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-teknik",
    promptText: "Termodinamika Teknik: Penerapan Hukum Termodinamika pada Siklus Daya dan Mesin Pendingin",
    badge: "Kuliah Teknik",
  },
  {
    id: "kuliah-teknik-2",
    title: "Mekanika Teknik: Analisis Tegangan & Regangan Bahan",
    reason: "Menghitung momen gaya dan beban lentur struktur bangunan.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-teknik",
    promptText: "Mekanika Teknik: Analisis Tegangan, Regangan, dan Momen Inersia Penampang Struktur",
    badge: "Kuliah Teknik",
  },
  {
    id: "kuliah-ekonomi-1",
    title: "Manajemen Keuangan Perusahaan: Valuation & Capital Budgeting",
    reason: "Menghitung Net Present Value (NPV) dan IRR investasi.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-ekonomi",
    promptText: "Manajemen Keuangan Korporat: Metode Capital Budgeting (NPV, IRR, Payback Period)",
    badge: "Kuliah Ekonomi",
  },
  {
    id: "kuliah-ekonomi-2",
    title: "Pengantar Ekonomi Mikro: Kurva Permintaan & Elastisitas",
    reason: "Teori perilaku konsumen dan keseimbangan pasar persaingan.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-ekonomi",
    promptText: "Ekonomi Mikro: Analisis Permintaan, Penawaran, dan Elastisitas Harga Pasar",
    badge: "Kuliah Ekonomi",
  },

  // ==================== KULIAH KESEHATAN, MIPA, SOSIAL ====================
  {
    id: "kuliah-kesehatan-1",
    title: "Farmakologi Dasar: Farmakokinetik & Farmakodinamik Obat",
    reason: "Proses absorpsi, distribusi, metabolisme, dan ekskresi obat.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-kesehatan",
    promptText: "Farmakologi Kedokteran: Memahami Prinsip Farmakokinetik dan Mekanisme Kerja Obat",
    badge: "Kuliah Kesehatan",
  },
  {
    id: "kuliah-mipa-1",
    title: "Kalkulus Multivariabel: Integral Lipat & Vektor Calculus",
    reason: "Materi tingkat lanjut jurusan Matematika dan Fisika MIPA.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-mipa",
    promptText: "Kalkulus Multivariabel: Integral Lipat Dua/Tiga, Teorema Green, dan Teorema Gauss",
    badge: "Kuliah MIPA",
  },
  {
    id: "kuliah-sosial-1",
    title: "Pengantar Hukum Indonesia: Perbedaan Perdata vs Pidana",
    reason: "Asas-asas hukum umum dan hukum acara di Indonesia.",
    categoryId: "kuliah",
    subCategoryId: "kuliah-sosial",
    promptText: "Pengantar Hukum Indonesia: Memahami Perbedaan Hukum Perdata dan Hukum Pidana",
    badge: "Kuliah Hukum",
  },

  // ==================== NGODING PEMULA ====================
  {
    id: "ngoding-pemula-1",
    title: "Pemrograman Python untuk Pemula dari Nol",
    reason: "Pengenalan variabel, tipe data, perulangan, dan fungsi.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-pemula",
    promptText: "Belajar Pemrograman Python dari Nol: Variabel, Tipe Data, Conditionals, dan Loops",
    badge: "Pemula",
  },
  {
    id: "ngoding-pemula-2",
    title: "HTML5 & CSS3 Dasar: Membuat Web Pertama",
    reason: "Struktur elemen HTML dan styling dengan CSS Flexbox.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-pemula",
    promptText: "Belajar HTML5 dan CSS3 dari Dasar: Membuat Tampilan Website Sederhana dan Responsive",
    badge: "Pemula",
  },
  {
    id: "ngoding-pemula-3",
    title: "Logika Pemrograman & Flowchart untuk Pemula",
    reason: "Cara berpikir analitis sebelum mulai menulis kode.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-pemula",
    promptText: "Dasar-Dasar Logika Pemrograman dan Pembuatan Flowchart untuk Pemula",
    badge: "Pemula",
  },

  // ==================== NGODING WEB ====================
  {
    id: "ngoding-web-1",
    title: "Fullstack Web Development: Next.js 15 & React 19",
    reason: "Teknologi pembuatan aplikasi web modern berskala produksi.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-web",
    promptText: "Fullstack Web Development: Panduan Membuat Web App dengan Next.js App Router & Tailwind CSS",
    badge: "Web Dev",
  },
  {
    id: "ngoding-web-2",
    title: "Rest API & GraphQL: Arsitektur Backend Web Modern",
    reason: "Menghubungkan aplikasi client dengan database via API.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-web",
    promptText: "Desain RESTful API & GraphQL: Best Practices, Otentikasi JWT, dan Penanganan Error",
    badge: "Web Dev",
  },
  {
    id: "ngoding-web-3",
    title: "React Hooks Lengkap: useState, useEffect, useMemo",
    reason: "Manajemen state dan efek samping di aplikasi React.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-web",
    promptText: "Mastering React Hooks: Penggunaan Praktis useState, useEffect, useRef, dan useMemo",
    badge: "Web Dev",
  },
  {
    id: "ngoding-web-4",
    title: "Web Security OWASP Top 10: XSS, CSRF, & SQL Injection",
    reason: "Amankan aplikasi web dari celah keamanan populer.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-web",
    promptText: "Keamanan Web OWASP Top 10: Mencegah SQL Injection, XSS, dan CSRF pada Aplikasi Web",
    badge: "Web Security",
  },

  // ==================== NGODING MOBILE, DATA, BACKEND, GAME ====================
  {
    id: "ngoding-mobile-1",
    title: "Mobile App Development dengan Flutter & Dart",
    reason: "Membuat aplikasi iOS dan Android sekaligus dengan satu codebase.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-mobile",
    promptText: "Belajar Flutter & Dart: Membuat Aplikasi Mobile Android dan iOS Berbasis State Management",
    badge: "Mobile Dev",
  },
  {
    id: "ngoding-data-1",
    title: "Data Science dengan Python: Pandas & Scikit-Learn",
    reason: "Pembersihan data, analisis eksploratif, dan pemodelan ML.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-data",
    promptText: "Data Science Praktis: Manipulasi Data dengan Pandas dan Pemodelan Machine Learning dengan Scikit-Learn",
    badge: "Data & AI",
  },
  {
    id: "ngoding-data-2",
    title: "Prompt Engineering & Integrasi OpenAI API",
    reason: "Membuat aplikasi berbasis LLM seperti ChatGPT Wrapper.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-data",
    promptText: "Panduan Prompt Engineering dan Integrasi OpenAI LLM API untuk Aplikasi Web",
    badge: "AI & LLM",
  },
  {
    id: "ngoding-backend-1",
    title: "Database PostgreSQL & Prisma ORM",
    reason: "Skema relasional, indeks, transaksi, dan query teroptimasi.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-backend",
    promptText: "Panduan Database PostgreSQL dan Prisma ORM: Skema Relasional, Indeks, dan Optimalisasi Query",
    badge: "Backend",
  },
  {
    id: "ngoding-backend-2",
    title: "Docker & Containerization untuk Developer",
    reason: "Membungkus aplikasi dalam container terisolasi.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-backend",
    promptText: "Panduan Docker untuk Pemula: Membuat Dockerfile, Docker Compose, dan Deploy Container",
    badge: "DevOps",
  },
  {
    id: "ngoding-game-1",
    title: "Game Development 2D/3D dengan Unity & C#",
    reason: "Fisika game, script karakter, dan sistem skor.",
    categoryId: "ngoding",
    subCategoryId: "ngoding-game",
    promptText: "Game Development Pemula: Membuat Game 2D Sederhana Menggunakan Unity Engine dan C#",
    badge: "Game Dev",
  },

  // ==================== SKILL & UMUM ====================
  {
    id: "skill-bahasa-1",
    title: "English for Business & Job Interviews",
    reason: "Persiapan menjawab pertanyaan wawancara kerja dalam Bahasa Inggris.",
    categoryId: "skill",
    subCategoryId: "skill-bahasa",
    promptText: "Panduan English for Business: Kosa Kata Profesional dan Jawaban Wawancara Kerja Inggris",
    badge: "Bahasa Inggris",
  },
  {
    id: "skill-bahasa-2",
    title: "Persiapan TOEFL iBT / IELTS: Strategy Listening & Reading",
    reason: "Tips menaikkan skor tes kemampuan bahasa Inggris.",
    categoryId: "skill",
    subCategoryId: "skill-bahasa",
    promptText: "Strategi Lolos Tes TOEFL / IELTS: Tips Mengerjakan Section Listening, Reading, dan Writing",
    badge: "TOEFL / IELTS",
  },
  {
    id: "skill-desain-1",
    title: "UI/UX Design Dasar: Figma & Wireframing",
    reason: "Prinsip hierarki visual, warna, dan pembuatan prototipe interaktif.",
    categoryId: "skill",
    subCategoryId: "skill-desain",
    promptText: "Desain UI/UX Pemula: Membuat Design System, Wireframe, dan Prototipe Interaktif di Figma",
    badge: "UI/UX",
  },
  {
    id: "skill-desain-2",
    title: "Adobe Photoshop: Photo Editing & Digital Compositing",
    reason: "Manipulasi foto, retouching, dan pembuatan poster promosi.",
    categoryId: "skill",
    subCategoryId: "skill-desain",
    promptText: "Panduan Photoshop Pemula: Teknik Selection Tool, Layer Masking, dan Color Grading",
    badge: "Desain Grafis",
  },
  {
    id: "skill-public-speaking-1",
    title: "Teknik Public Speaking & Presentasi Memikat",
    reason: "Mengatasi rasa gugup, intonasi vokal, dan bahasa tubuh.",
    categoryId: "skill",
    subCategoryId: "skill-public-speaking",
    promptText: "Panduan Public Speaking: Cara Menyusun Slide Presentasi dan Berbicara Percaya Diri di Depan Publik",
    badge: "Communication",
  },
  {
    id: "skill-public-speaking-2",
    title: "Technical Writing: Menulis Dokumentasi Software",
    reason: "Kemampuan menyusun panduan pengguna dan dokumentasi API yang jelas.",
    categoryId: "skill",
    subCategoryId: "skill-public-speaking",
    promptText: "Technical Writing: Cara Menulis Dokumentasi API dan User Guide yang Rapi serta Mudah Dipahami",
    badge: "Writing",
  },
  {
    id: "skill-finance-1",
    title: "Manajemen Keuangan Pribadi & Investasi Pemula",
    reason: "Alokasi gaji, dana darurat, dan pengenalan instrumen investasi.",
    categoryId: "skill",
    subCategoryId: "skill-finance",
    promptText: "Keuangan Pribadi: Strategi Penganggaran 50/30/20, Dana Darurat, dan Dasar Investasi",
    badge: "Finance",
  },
  {
    id: "skill-finance-2",
    title: "Digital Marketing & E-Commerce Strategy",
    reason: "Social media ads, SEO, dan optimasi toko online.",
    categoryId: "skill",
    subCategoryId: "skill-finance",
    promptText: "Digital Marketing Strategy: Cara Menjalankan Facebook Ads, Google SEO, dan Content Funnel",
    badge: "Marketing",
  },
];
